apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-vwtp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-java-springboot-basic-vwtp
    app.kubernetes.io/part-of: my-app
  name: devfile-sample-java-springboot-basic-vwtp
spec:
  rules:
  - host: devfile-sample-java-springboot-basic-vwtp-jfischer-tenant.byoc.apps.ci-ln-ql40ttt-72292.origin-ci-int-gce.dev.rhcloud.com
    http:
      paths:
      - backend:
          service:
            name: devfile-sample-java-springboot-basic-vwtp
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
